Repository jfrog/froggit-go, pull requests merged in 2023-06, with the labels that each got.

#91 Update test workflows to go 1.20
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/test.yml
Labels: ignore for release

#90 Fix GitLab pull request state parameter
  vcsclient/gitlab.go
  vcsclient/gitlab_test.go
  vcsclient/testdata/gitlab/pull_requests_list_response.json
Labels: bug

#95 Add the ability to update pull requests metadata
  go.mod
  go.sum
  vcsclient/azurerepos.go
  vcsclient/azurerepos_test.go
  vcsclient/bitbucketcloud.go
  vcsclient/bitbucketcloud_test.go
  vcsclient/bitbucketserver.go
  vcsclient/bitbucketserver_test.go
  vcsclient/github.go
  vcsclient/github_test.go
  vcsclient/gitlab.go
  vcsclient/gitlab_test.go
  vcsclient/logger.go
  vcsclient/vcsclient.go
  vcsutils/consts.go
  vcsutils/utils.go
  vcsutils/utils_test.go
Labels: new feature

#96 Update docs
  README.md
  vcsclient/github_test.go
Labels: ignore for release
