Repository jfrog/froggit-go, pull requests merged in 2023-02, with the labels that each got.

#68 Update CLA assistant
  .github/workflows/cla.yml
Labels: ignore for release

#67 Add GetModifiedFiles
  README.md
  go.mod
  go.sum
  vcsclient/azurerepos.go
  vcsclient/azurerepos_test.go
  vcsclient/bitbucketcloud.go
  vcsclient/bitbucketcloud_test.go
  vcsclient/bitbucketserver.go
  vcsclient/bitbucketserver_test.go
  vcsclient/github.go
  vcsclient/github_test.go
  vcsclient/gitlab.go
  vcsclient/gitlab_test.go
  vcsclient/testdata/azurerepos/compare_commits.json
  vcsclient/testdata/azurerepos/resourcesResponse.json
  vcsclient/testdata/bitbucketcloud/compare_commits.json
  vcsclient/testdata/bitbucketserver/compare_commits.json
  vcsclient/testdata/github/compare_commits.json
  vcsclient/testdata/gitlab/compare_commits.json
  vcsclient/vcsclient.go
  vcsutils/utils.go
  vcsutils/utils_test.go
Labels: new feature

#69 Fix documentation in vcsclient.go
  vcsclient/vcsclient.go
Labels: ignore for release

#71 Add .git initialization on DownloadRepository for GitLab
  vcsclient/gitlab.go
  vcsclient/gitlab_test.go
Labels: bug
