Repository jfrog/froggit-go, pull requests merged in 2023-05, with the labels that each got.

#82 Fix Azure DevOps commit statuses functions
  vcsclient/azurerepos.go
Labels: bug

#84 Fix wrong status code in Bitbucket Server DownloadRepository API
  vcsclient/bitbucketserver.go
Labels: bug

#83 Fix GitHub cloud remote URLs
  vcsclient/github.go
  vcsclient/github_test.go
  vcsutils/utils_test.go
Labels: bug

#81 Allow to listen for tag webhook events
  vcsclient/bitbucketcloud.go
  vcsclient/bitbucketcloud_test.go
  vcsclient/bitbucketserver.go
  vcsclient/bitbucketserver_test.go
  vcsclient/github.go
  vcsclient/github_test.go
  vcsclient/gitlab.go
  vcsclient/gitlab_test.go
Labels: improvement

#88 Update frogbot workflow & Go to 1.20.x
  .github/workflows/frogbot-scan-and-fix.yml
  go.mod
Labels: ignore for release
