Repository jfrog/froggit-go, pull requests merged in 2023-07, with the labels that each got.

#97 Standardize ListOpenPullRequest responses
  vcsclient/bitbucketserver.go
  vcsclient/bitbucketserver_test.go
  vcsclient/testdata/bitbucketserver/pull_requests_list_response.json
Labels: bug

#98 Add pull request body to ListOpenPullRequests
  README.md
  vcsclient/azurerepos.go
  vcsclient/azurerepos_test.go
  vcsclient/bitbucketcloud.go
  vcsclient/bitbucketcloud_test.go
  vcsclient/bitbucketserver.go
  vcsclient/bitbucketserver_test.go
  vcsclient/github.go
  vcsclient/github_test.go
  vcsclient/gitlab.go
  vcsclient/gitlab_test.go
  vcsclient/testdata/bitbucketcloud/pull_requests_list_response.json
  vcsclient/testdata/bitbucketserver/pull_requests_list_response.json
  vcsclient/testdata/github/pull_requests_list_response.json
  vcsclient/testdata/gitlab/pull_requests_list_response.json
  vcsclient/vcsclient.go
Labels: improvement

#92 Add GetPullRequest by ID
  README.md
  vcsclient/azurerepos.go
  vcsclient/azurerepos_test.go
  vcsclient/bitbucketcloud.go
  vcsclient/bitbucketcloud_test.go
  vcsclient/bitbucketserver.go
  vcsclient/bitbucketserver_test.go
  vcsclient/github.go
  vcsclient/github_test.go
  vcsclient/gitlab.go
  vcsclient/gitlab_test.go
  vcsclient/logger.go
  vcsclient/testdata/azurerepos/resourcesResponse.json
  vcsclient/testdata/bitbucketcloud/get_pull_request_response.json
  vcsclient/testdata/bitbucketserver/get_pull_request_response.json
  vcsclient/testdata/github/pull_request_info_response.json
  vcsclient/testdata/github/pull_request_info_response_bad_labels.json
  vcsclient/testdata/gitlab/get_merge_request_response.json
  vcsclient/vcsclient.go
Labels: new feature

#101 Fix panic when response is nil in DownloadRepoFromFile
  vcsclient/bitbucketserver.go
  vcsclient/github.go
  vcsclient/gitlab.go
Labels: bug

#99 Remove Pull Request comment
  vcsclient/azurerepos.go
  vcsclient/azurerepos_test.go
  vcsclient/bitbucketcloud.go
  vcsclient/bitbucketserver.go
  vcsclient/bitbucketserver_test.go
  vcsclient/github.go
  vcsclient/github_test.go
  vcsclient/gitlab.go
  vcsclient/gitlab_test.go
  vcsclient/testdata/azurerepos/resourcesResponse.json
  vcsclient/vcsclient.go
Labels: new feature

#104 Improve tests, Add GolangCI static analysis and Update dependencies
  .github/workflows/cla.yml
  .github/workflows/test.yml
  README.md
  go.mod
  go.sum
  vcsclient/azurerepos.go
  vcsclient/azurerepos_test.go
  vcsclient/bitbucketcloud.go
  vcsclient/bitbucketcloud_test.go
  vcsclient/bitbucketcommon_test.go
  vcsclient/bitbucketserver.go
  vcsclient/bitbucketserver_test.go
  vcsclient/github.go
  vcsclient/github_test.go
  vcsclient/gitlab.go
  vcsclient/gitlab_test.go
  vcsclient/testdata/bitbucketserver/add_ssh_key_response.json
  vcsclient/testdata/bitbucketserver/pull_requests_list_response.json
  vcsclient/testdata/bitbucketserver/repository_response.json
  vcsclient/testdata/github/commits_statuses.json
  vcsclient/testdata/github/commits_statuses_bad_json.json
  vcsclient/testdata/github/compare_commits.json
  vcsclient/testdata/gitlab/projects_response.json
  vcsclient/testdata/gitlab/pull_requests_list_response.json
  vcsclient/testdata/gitlab/repository_response.json
  vcsclient/validate_required_params_test.go
  vcsutils/utils.go
  vcsutils/utils_test.go
  vcsutils/webhookparser/bitbucketcloud_test.go
  vcsutils/webhookparser/bitbucketserver_test.go
  vcsutils/webhookparser/github_test.go
  vcsutils/webhookparser/gitlab.go
  vcsutils/webhookparser/gitlab_test.go
  vcsutils/webhookparser/webhookparser.go
Labels: improvement

#103 Fix missing Git owner issue on bitbucket and gitlab
  vcsclient/bitbucketserver.go
  vcsclient/bitbucketserver_test.go
  vcsclient/gitlab.go
  vcsclient/gitlab_test.go
  vcsclient/testdata/bitbucketserver/pull_requests_list_response.json
Labels: bug

#106 Fix GetPullRequestByID
  vcsclient/bitbucketserver.go
  vcsclient/github.go
  vcsclient/gitlab.go
  vcsclient/gitlab_test.go
  vcsclient/testdata/gitlab/get_project_response.json
  vcsclient/testdata/gitlab/pull_requests_list_response.json
  vcsutils/utils.go
Labels: bug
